### ISSUE TITLE
Kode sumber kbbi-api-zhirrr.vercel.app?

### ISSUE THREAD

**Issue by w3teal** [JastinXyz/kbbi.js#1]
Di seluruh respository, tidak ada data javascript untuk kata-kata kbbinya. Itu hanya menggunakan API dari kbbi-api-zhirrr.vercel.app yang tidak dijelaskan di repository ini.
Apakah ada source code dari website kbbi-api-zhirrr.vercel.app?

**Comment by JastinXyz** [comment]
Jika anda sedang mencari source code dari kbbi-api-zhirrr.vercel.app, coba lihat kode di package npm mereka: https://www.npmjs.com/package/zahir-api?activeTab=code 🙂

**Comment by w3teal** [comment]
> Jika anda sedang mencari source code dari kbbi-api-zhirrr.vercel.app, coba lihat kode di package npm mereka: https://www.npmjs.com/package/zahir-api?activeTab=code 🙂

@JastinXyz, Saya lihat link repositorinya tidak bekerja. Dan ketika saya mencari repositorinya di GitHub juga tidak ada. Apakah akun [zhirr](https://www.npmjs.com/~zhirrr) sudah tidak aktif? Dan juga terakhir kali diupdate 3 tahun yang lalu.

**Comment by JastinXyz** [comment]
@LIGMATV Saya juga kurang mengetahui tentang akun atau repository tersebut, tapi mungkin jika anda sedang mencari kode sumber KBBI di package itu, anda bisa ke menu "Code" yang ada di [npmjs.com/zahir-api](https://www.npmjs.com/package/zahir-api) lalu ke file `/lib/KBBI.js`, mungkin itu akan membantu anda?
